CC=g++    # someday maybe we'll be able to say CC=g++!
CFLAGS=-lncurses -std=c++11
TARGETS=window1 window2 window3 window4 window5 window6 window7 window8
#       
main: $(TARGETS)



# The following line shows how to produce .o files from .cc files
#.cc.o:
#$(CC) -c $(CFLAGS) $*.cc -o $*.o
clean:
	rm *.o window?
